apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moge2-model-cache
  namespace: geometry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: cfs
