apiVersion: v1
kind: Service
metadata:
  name: moge2-geometry-service
  namespace: geometry
spec:
  selector:
    app: moge2-geometry-service
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
